language: java
install: true

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
    - sshpass

script:
  - mvn verify -Dserver.host=$LOGISTICS_HOST -Dserver.port=$LOGISTICS_PORT

cache:
  directories:
    - '$HOME/.m2/repository'

after_success:
  - sshpass -p $FTP_PASSWORD scp -o StrictHostKeyChecking=no -o BatchMode=no -r target/jmeter/reports/test-plan_*_* $FTP_USER@esign.com.br:public_html/logistics-test-jmeter
